Support for ODS files and for chosing between A4 and Letter paper sizes.

diff --git a/pdf2odt b/pdf2odt
--- a/pdf2odt
+++ b/pdf2odt
@@ -2,11 +2,10 @@
 
 # Usage: pdf2odt input.pdf ... output.odt
 #
-# This script converts one or more PDF, JPG, or PNG files to an ODT file.
-# The contents of any PDF file(s) is first converted to a set of image
-# files. These files are then inserted as background images in the ODT file.
-#
-# N.B.: The script always generates ODT files that have letter format.
+# This script converts one or more PDF, JPG, or PNG files to an ODT or ODS
+# file. The contents of any PDF file(s) is first converted to a set of image
+# files. These files are then inserted as background images in the ODT or
+# ODS file.
 #
 # Copyright (c) 2011 Markus Gutschke. All rights reserved.
 #
@@ -28,28 +27,103 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
+export LC_ALL=C
 
 # Check arguments
 [ $# -ge 2 ] || {
   echo "Usage:" >&2
-  echo "  $(basename "$0") [ options ] input.{jpg,pdf,png} ... output.odt" >&2
+  echo "  $(basename "$0") [ options ] input.{jpg,pdf,png} ... output.{odt,ods}" >&2
   echo >&2
   echo "Options:" >&2
-  echo "  --                 Stop scanning for options." >&2
-  echo "  --resolution=RES   Change resolution of embedded images." >&2
-  echo "                     Only affects PDF files. PDF/PNG files will not" >&2
-  echo "                     be rescaled." >&2
+  echo "  --                   Stop scanning for options." >&2
+  echo "  --format={odt|ods}   Select output file format." >&2
+  echo "  --paper={letter|a4}  Select paper size." >&2
+  echo "  --resolution=RES     Change resolution of embedded images." >&2
+  echo "                       Only affects PDF files. PDF/PNG files will not" >&2
+  echo "                       be rescaled." >&2
   exit 1
 }
 
-# Don't overwrite the output file, unless it is an ODT file already.
+# Attempt to deduce the output file format from the output file name.
+eval out="\${$#}"
+format="${out##*.}"; format="${format,,}"
+[ "x${format}" = "xodt" -o "x${format}" = "xods" ] || format="odt"
+
+# Select default papersize.
+papersize="${PAPERSIZE:-$(cat "${PAPERCONF:-/etc/papersize}" 2>/dev/null)}"
+[ "x${papersize}" != "a4" ] && papersize="letter"
+
+# Parse position-independent command line flags.
+pdf=("$@"); unset pdf[$((${#pdf[@]}-1))]
+i=0; while [ $i -lt ${#pdf[@]} ]; do
+  if [ "x${pdf[$i]#-}" != "x${pdf[$i]}" ]; then
+    case "${pdf[$i]}" in
+      --)
+        break
+        ;;
+      --format*)
+        if [ "x${pdf[$i]#--format=}" != "x${pdf[$i]}" ]; then
+          format="${pdf[$i]#--format=}"
+        else
+          i=$(($i + 1))
+          format="${pdf[$i]}"
+        fi
+        format="${format,,}"
+        if [ "x${format}" != "xodt" -a "x${format}" != "xods" ]; then
+          echo "Unsupported output format \"${format}\"." >&2
+          exit 1
+        fi
+        ;;
+      --paper*)
+        if [ "x${pdf[$i]#--paper=}" != "x${pdf[$i]}" ]; then
+          papersize="${pdf[$i]#--paper=}"
+        else
+          i=$(($i + 1))
+          papersize="${pdf[$i]}"
+        fi
+        if [ "x${papersize}" != "xletter" -a "x${papersize}" != "xa4" ]; then
+          echo "Unsupported paper size \"${papersize}\" provided." >&2
+          exit 1
+        fi
+        ;;
+      --resolution*)
+        if [ "x${pdf[$i]#--resolution=}" = "x${pdf[$i]}" ]; then
+          i=$(($i + 1))
+        fi
+        ;;
+      *)
+        echo "Unknown command line option \"${pdf[$i]}\"." >&2
+        exit 1
+        ;;
+    esac
+  else
+    if [ ! -r "${pdf[$i]}" ]; then
+      echo "Invalid or non-existent filename \"${pdf[$i]}\"." >&2
+      exit 1
+    fi
+  fi
+  i=$(($i + 1))
+done
+[ "${format}" = odt ] && formatname="Text" || formatname="Spreadsheet"
+if [ "${papersize}" = "letter" ]; then
+  units="in"
+  units2inch="1"
+  width="8.5"
+  height="11"
+else
+  units="mm"
+  units2inch="25.4"
+  width="210"
+  height="297"
+fi
+
+# Don't overwrite the output file, unless it is an ODT/ODS file already.
 # This protects users from overwriting input files, if they completely
 # forgot to specify any output file.
-eval odt="\${$#}"
-if [ -e "${odt}" ] &&
-   [[ ! "$(file "${odt}" 2>/dev/null)" =~ "OpenDocument Text" ]]; then
-  echo "Did you forget to specify the output file name? \"${odt}\"" \
-       "exists, but is not an ODT file" >&2
+if [ -e "${out}" ] &&
+   [[ ! "$(file "${out}" 2>/dev/null)" =~ "OpenDocument ${formatname}" ]]; then
+  echo "Did you forget to specify the output file name? \"${out}\"" \
+       "exists, but is not an ${format^^} file" >&2
   exit 1
 fi
 
@@ -64,7 +138,6 @@ mkdir -p "${TMPDIR}"
 
 # Preprocess image file(s), and convert PDF file(s) to images
 mkdir -p "${TMPDIR}/Pictures"
-pdf=("$@"); unset pdf[$((${#pdf[@]}-1))]
 endofargs=
 resolution=300
 i=0; while [ $i -lt ${#pdf[@]} ]; do
@@ -72,6 +145,16 @@ i=0; while [ $i -lt ${#pdf[@]} ]; do
     case "${pdf[$i]}" in
       --)
         endofargs=t
+        ;;
+      --format*)
+        if [ "x${pdf[$i]#--format=}" = "x${pdf[$i]}" ]; then
+          i=$(($i + 1))
+        fi
+        ;;
+      --paper*)
+        if [ "x${pdf[$i]#--paper=}" = "x${pdf[$i]}" ]; then
+          i=$(($i + 1))
+        fi
         ;;
       --resolution*)
         if [ "x${pdf[$i]#--resolution=}" != "x${pdf[$i]}" ]; then
@@ -92,20 +175,16 @@ i=0; while [ $i -lt ${#pdf[@]} ]; do
         ;;
     esac
   else
-    if [ ! -r "${pdf[$i]}" ]; then
-      echo "Invalid or non-existent filename \"${pdf[$i]}\"." >&2
-      exit 1
-    fi
-    suffix="$(echo "${pdf[$i]##*.}"|tr A-Z a-z)"
+    suffix="${pdf[$i]##*.}"; suffix="${suffix,,}"
     n=$(($(ls "${TMPDIR}/Pictures/Image-"* 2>/dev/null | wc -l) + 1))
     case "$suffix" in
       png|jpg|jpeg)
         if [ "$suffix" = "jpg" ]; then suffix="jpeg"; fi
-        # Adjust DPI so that the image fits on a letter-sized page.
+        # Adjust DPI so that the image fits on a letter- or a4-sized page.
         res="$(identify "${pdf[$i]}")"
         res="$(echo "x ${res#${pdf[i]}}"|awk '{ print $3 }')"
-        dpiX=$((2*${res%x*}/17))
-        dpiY=$((${res#*x}/11))
+        dpiX=$(dc -e "${res%x*} ${width} ${units2inch}//p")
+        dpiY=$(dc -e "${res#*x} ${height} ${units2inch}//p")
         if [ ${dpiX} -gt ${dpiY} ]; then dpi="${dpiX}"; else dpi="${dpiY}"; fi
         convert "${pdf[$i]}" -set units PixelsPerInch -set density "${dpi}" \
                 "${TMPDIR}/Pictures/Image-$(printf '%03d' $n).$suffix"
@@ -126,23 +205,25 @@ done
 mkdir -p "${TMPDIR}/META-INF"
 
 # Create "mimetype" file
-printf '%s' 'application/vnd.oasis.opendocument.text' >"${TMPDIR}/mimetype"
+printf '%s' "application/vnd.oasis.opendocument.${formatname,,}" >"${TMPDIR}/mimetype"
 
 # Create "META-INF/manifest.xml" file
-cat >"${TMPDIR}/META-INF/manifest.xml" <<'EOF'
+{ cat <<EOF
 <?xml version="1.0" encoding="UTF-8"?>
 <manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0">
-  <manifest:file-entry manifest:media-type="application/vnd.oasis.opendocument.text" manifest:version="1.2" manifest:full-path="/"/>
+  <manifest:file-entry manifest:media-type="application/vnd.oasis.opendocument.${formatname,,}" manifest:version="1.2" manifest:full-path="/"/>
   <manifest:file-entry manifest:media-type="text/xml" manifest:full-path="content.xml"/>
   <manifest:file-entry manifest:media-type="text/xml" manifest:full-path="styles.xml"/>
-  <manifest:file-entry manifest:media-type="" manifest:full-path="Pictures/"/>
 EOF
+[ "${format}" = "ods" ] &&
+  echo '  <manifest:file-entry manifest:media-type="text/xml" manifest:full-path="settings.xml"/>'
 ls "${TMPDIR}/Pictures/"*.{png,jpeg} 2>/dev/null | sort | \
-  sed 's/^.*\/Pictures\/\([^.]*[.]\)\(.*\)/  <manifest:file-entry manifest:media-type="image\/\2" manifest:full-path="Pictures\/\1\2/;s/$/"\/>/' >>"${TMPDIR}/META-INF/manifest.xml"
-echo '</manifest:manifest>' >>"${TMPDIR}/META-INF/manifest.xml"
+  sed 's/^.*\/Pictures\/\([^.]*[.]\)\(.*\)/  <manifest:file-entry manifest:media-type="image\/\2" manifest:full-path="Pictures\/\1\2/;s/$/"\/>/'
+echo '</manifest:manifest>'; } >"${TMPDIR}/META-INF/manifest.xml"
 
 # Create "content.xml" file
-cat >"${TMPDIR}/content.xml" <<'EOF'
+if [ "${format}" = "odt" ]; then
+cat <<'EOF'
 <?xml version="1.0" encoding="UTF-8"?>
 <office:document-content
  xmlns:grddl="http://www.w3.org/2003/g/data-view#"
@@ -154,22 +235,99 @@ cat >"${TMPDIR}/content.xml" <<'EOF'
   <office:automatic-styles>
 EOF
 ls "${TMPDIR}/Pictures/"*.{png,jpeg} 2>/dev/null | sort | \
-  sed 's/^.*\/Pictures\/Image-\([0-9]*\)[.].*/    <style:style style:name="Image\1" style:family="paragraph" style:master-page-name="Image\1"><style:paragraph-properties style:page-number="auto"\/><\/style:style>/' >>"${TMPDIR}/content.xml"
-cat >>"${TMPDIR}/content.xml" <<'EOF'
+  sed 's/^.*\/Pictures\/Image-\([0-9]*\)[.].*/    <style:style style:name="Image\1" style:family="paragraph" style:master-page-name="Image\1"><style:paragraph-properties style:page-number="auto"\/><\/style:style>/'
+cat <<'EOF'
   </office:automatic-styles>
   <office:body>
     <office:text text:use-soft-page-breaks="true">
 EOF
 ls "${TMPDIR}/Pictures/"*.{png,jpeg} 2>/dev/null | sort | \
-  sed 's/^.*\/Pictures\/Image-\([0-9]*\)[.].*/      <text:p text:style-name="Image\1"\/>/' >>"${TMPDIR}/content.xml"
-cat >>"${TMPDIR}/content.xml" <<'EOF'
+  sed 's/^.*\/Pictures\/Image-\([0-9]*\)[.].*/      <text:p text:style-name="Image\1"\/>/'
+cat <<'EOF'
     </office:text>
   </office:body>
 </office:document-content>
 EOF
+else
+if [ "${papersize}" = "letter" ]; then
+  xcs="0.03125" # 1/32"
+  ycs="0.03125" # 1/32"
+  ucs="in"
+  u2i="1"
+else
+  xcs="0.75"
+  ycs="0.75"
+  ucs="mm"
+  u2i="25.4"
+fi
+wcs="$(dc -e "10k ${width}  ${units2inch}/ ${xcs} ${u2i}/0k/p")"
+hcs="$(dc -e "10k ${height} ${units2inch}/ ${ycs} ${u2i}/0k/p")"
+col="$(dc -e "${wcs} [1 - d 26 % 65 + a r 26 / d 0 !=a] sa lax sa [n z 0 !=a]sa lax")"
+cat <<EOF
+<?xml version="1.0" encoding="UTF-8"?>
+<office:document-content
+ xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
+ xmlns:calcext="urn:org:documentfoundation:names:experimental:calc:xmlns:calcext:1.0"
+ xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
+ xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
+ xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
+ xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"
+ xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
+ xmlns:xlink="http://www.w3.org/1999/xlink"
+ office:version="1.2">
+  <office:automatic-styles>
+    <style:style style:name="co1" style:family="table-column">
+      <style:table-column-properties style:column-width="${xcs}${ucs}"/>
+    </style:style>
+    <style:style style:name="ro1" style:family="table-row">
+      <style:table-row-properties style:row-height="${ycs}${ucs}"/>
+    </style:style>
+  </office:automatic-styles>
+  <office:body>
+    <office:spreadsheet>
+EOF
+ls "${TMPDIR}/Pictures/"*.{png,jpeg} 2>/dev/null | sort | \
+ while read -r file; do
+  idx="${file#${TMPDIR}/Pictures/Image-}"; idx="$(dc -e "${idx%.*}p")"
+  res="$(identify "${file}")"
+  res="$(echo "x ${res#${file}}"|awk '{ print $3 }')"
+  trim='/[.]/b1;q;:1;s/\([1-9]\)0*$/\1/;s/[.]0*$//'
+  round=' 8k1/0.00000005+6k1/'
+  iwu="$(dc -e "10k ${height} ${res#*x}/${res%x*}*ddsa ${width} dsb [lb]sc<c ${units2inch}/${u2i}*${round}p"|sed "${trim}")"
+  ihu="$(dc -e "10k ${width}  ${res%x*}/${res#*x}*ddsa ${height}dsb [lb]sc<c ${units2inch}/${u2i}*${round}p"|sed "${trim}")"
+  ilo="$(dc -e "10k ${width}  ${units2inch}/${u2i}* ${iwu}- 2/${round}p"|sed -e "${trim}")"
+  ito="$(dc -e "10k ${height} ${units2inch}/${u2i}* ${ihu}- 2/${round}p"|sed -e "${trim}")"
+  cat <<EOF
+      <table:table table:name="Sheet${idx}" table:print-ranges="Sheet${idx}.A1:Sheet${idx}.${col}${hcs}">
+        <table:shapes>
+          <draw:frame draw:z-index="0" draw:name="Image ${idx}" table:table-background="true" svg:width="${iwu}${ucs}" svg:height="${ihu}${ucs}" svg:x="${ilo}${ucs}" svg:y="${ito}${ucs}">
+            <draw:image xlink:href="${file#${TMPDIR}/}" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad">
+            </draw:image>
+          </draw:frame>
+        </table:shapes>
+        <table:table-column table:style-name="co1" table:number-columns-repeated="${wcs}"/>
+        <table:table-row table:style-name="ro1" table:number-rows-repeated="$((hcs-1))">
+          <table:table-cell table:number-columns-repeated="${wcs}"/>
+        </table:table-row>
+        <table:table-row table:style-name="ro1">
+          <table:table-cell table:number-columns-repeated="$((wcs-1))"/>
+          <table:table-cell office:value-type="string" calcext:value-type="string">
+            <text:p><text:s/></text:p>
+          </table:table-cell>
+        </table:table-row>
+      </table:table>
+EOF
+  done
+cat <<'EOF'
+    </office:spreadsheet>
+  </office:body>
+</office:document-content>
+EOF
+fi >"${TMPDIR}/content.xml"
 
 # Create "styles.xml" file
-cat >"${TMPDIR}/styles.xml" <<'EOF'
+if [ "${format}" = "odt" ]; then
+cat <<'EOF'
 <?xml version="1.0" encoding="UTF-8"?>
 <office:document-styles xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
  xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
@@ -181,24 +339,81 @@ cat >"${TMPDIR}/styles.xml" <<'EOF'
   <office:automatic-styles>
 EOF
 ls "${TMPDIR}/Pictures/"*.{png,jpeg} 2>/dev/null | sort | \
-  sed 's/^.*\/Pictures\/Image-\([0-9]*\)[.]\(.*\)/    <style:page-layout style:name="Image\1"><style:page-layout-properties fo:page-width="8.5in" fo:page-height="11in" style:num-format="1" style:print-orientation="portrait" fo:margin-top="0in" fo:margin-bottom="0in" fo:margin-left="0in" fo:margin-right="0in" fo:background-color="transparent" style:writing-mode="lr-tb" style:footnote-max-height="0in"><style:background-image xlink:href="Pictures\/Image-\1.\2" xlink:type="simple" xlink:actuate="onLoad" style:position="center center" style:repeat="no-repeat"\/><\/style:page-layout-properties><\/style:page-layout>/' >>"${TMPDIR}/styles.xml"
-cat >>"${TMPDIR}/styles.xml" <<'EOF'
+  sed 's/^.*\/Pictures\/Image-\([0-9]*\)[.]\(.*\)/    <style:page-layout style:name="Image\1"><style:page-layout-properties fo:page-width="'"${width}${units}"'" fo:page-height="'"${height}${units}"'" style:num-format="1" style:print-orientation="portrait" fo:margin-top="0in" fo:margin-bottom="0in" fo:margin-left="0in" fo:margin-right="0in" fo:background-color="transparent" style:writing-mode="lr-tb" style:footnote-max-height="0in"><style:background-image xlink:href="Pictures\/Image-\1.\2" xlink:type="simple" xlink:actuate="onLoad" style:position="center center" style:repeat="no-repeat"\/><\/style:page-layout-properties><\/style:page-layout>/'
+cat <<'EOF'
   </office:automatic-styles>
   <office:master-styles>
 EOF
 ls "${TMPDIR}/Pictures/"*.{png,jpeg} 2>/dev/null | sort | \
-  sed 's/^.*\/Pictures\/Image-\([0-9]*\)[.].*/    <style:master-page style:name="Image\1" style:page-layout-name="Image\1"\/>/' >>"${TMPDIR}/styles.xml"
-cat >>"${TMPDIR}/styles.xml" <<'EOF'
+  sed 's/^.*\/Pictures\/Image-\([0-9]*\)[.].*/    <style:master-page style:name="Image\1" style:page-layout-name="Image\1"\/>/'
+cat <<'EOF'
   </office:master-styles>
 </office:document-styles>
 EOF
+else
+cat <<EOF
+<?xml version="1.0" encoding="UTF-8"?>
+<office:document-styles xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
+ xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
+ xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
+ office:version="1.2">
+  <office:styles>
+    <style:default-style style:family="graphic">
+      <style:paragraph-properties style:font-independent-line-spacing="true"/>
+      <style:text-properties style:font-family-generic="roman" style:font-pitch="variable" fo:font-size="0pt"/>
+    </style:default-style>
+  </office:styles>
+  <office:automatic-styles>
+    <style:page-layout style:name="PageLayout">
+      <style:page-layout-properties fo:margin-top="0in" fo:margin-bottom="0in" fo:margin-left="0in" fo:margin-right="0in" fo:page-width="${width}${units}" fo:page-height="${height}${units}" style:scale-to-pages="1"/>
+      <style:header-style>
+        <style:header-footer-properties fo:min-height="0in" fo:margin-left="0in" fo:margin-right="0in" fo:margin-bottom="0in"/>
+      </style:header-style>
+      <style:footer-style>
+        <style:header-footer-properties fo:min-height="0in" fo:margin-left="0in" fo:margin-right="0in" fo:margin-top="0in"/>
+      </style:footer-style>
+    </style:page-layout>
+  </office:automatic-styles>
+  <office:master-styles>
+    <style:master-page style:name="Default" style:page-layout-name="PageLayout">
+      <style:header style:display="false"/>
+      <style:header-left style:display="false"/>
+      <style:footer style:display="false"/>
+      <style:footer-left style:display="false"/>
+    </style:master-page>
+  </office:master-styles>
+</office:document-styles>
+EOF
+fi >"${TMPDIR}/styles.xml"
 
-# Pack individual files into ODT archive
-[ "x${odt}" = "x${odt#/}" ] && odt="${PWD}/${odt}" || :
-rm -f "${odt}"
+# Create "settings.xml" file
+if [ "${format}" = "ods" ]; then
+cat >>"${TMPDIR}/settings.xml" <<'EOF'
+<?xml version="1.0" encoding="UTF-8"?>
+<office:document-settings
+ xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
+ xmlns:config="urn:oasis:names:tc:opendocument:xmlns:config:1.0"
+ xmlns:ooo="http://openoffice.org/2004/office"
+ office:version="1.2">
+  <office:settings>
+    <config:config-item-set config:name="ooo:view-settings">
+      <config:config-item-map-indexed config:name="Views">
+        <config:config-item-map-entry>
+          <config:config-item config:name="ShowGrid" config:type="false">true</config:config-item>
+        </config:config-item-map-entry>
+      </config:config-item-map-indexed>
+    </config:config-item-set>
+  </office:settings>
+</office:document-settings>
+EOF
+fi
+
+# Pack individual files into ODT/ODS archive
+[ "x${out}" = "x${out#/}" ] && out="${PWD}/${out}" || :
+rm -f "${out}"
 cd "${TMPDIR}" &&
-  zip -m -q -X -0 "${odt}" mimetype &&
-  zip -m -q -X    "${odt}" $(find . -name mimetype -o -type f -print) &&
+  zip -m -q -X -0 "${out}" mimetype &&
+  zip -m -q -X    "${out}" $(find . -name mimetype -o -type f -print) &&
   cd ..
 
 # Clean up
